### ISSUE TITLE
1.0.0-ALPHA-4 build project error

### ISSUE THREAD

**Issue by weijunfeng** [rickclephas/KMP-NativeCoroutines#89]
When I use the 1.0.0-ALPHA-4 version to build the project, an error is reported, and the error message is as follows

A problem occurred configuring project ':lib-sdk'.
> Failed to notify project evaluation listener.
   > Cannot change attributes of dependency configuration ':lib-sdk:iosX64ApiElements' after it has been resolved
   > Cannot change attributes of dependency configuration ':lib-sdk:podDebugFrameworkIosX64' after it has been resolved
   > Cannot change attributes of dependency configuration ':lib-sdk:podDebugFrameworkIosFat' after it has been resolved
   > Cannot change attributes of dependency configuration ':lib-sdk:podReleaseFrameworkIosX64' after it has been resolved
   > Cannot change attributes of dependency configuration ':llib-sdk:podReleaseFrameworkIosFat' after it has been resolved
   > Cannot change attributes of dependency configuration ':lib-sdk:iosArm64ApiElements' after it has been resolved
   > Cannot change attributes of dependency configuration ':lib-sdk:podDebugFrameworkIosArm64' after it has been resolved
   > Cannot change attributes of dependency configuration ':lib-sdk:podReleaseFrameworkIosArm64' after it has been resolved
   > Cannot change attributes of dependency configuration ':lib-sdk:iosSimulatorArm64ApiElements' after it has been resolved
   > Cannot change attributes of dependency configuration ':lib-sdk:podDebugFrameworkIosSimulatorArm64' after it has been resolved
   > Cannot change attributes of dependency configuration ':lib-sdk:podReleaseFrameworkIosSimulatorArm64' after it has been resolved

what is the reason？

**Comment by rickclephas** [comment]
Hi! Thanks for reporting this.
Could you share some more information about your setup, project structure and gradle files?

**Comment by weijunfeng** [comment]
I tried to fix this problem and found that commenting out the following code build project did not report this error
```
//            kotlin.targets.filter { it.isKmpNativeCoroutinesTarget }.map { target ->
//                "ksp${target.targetName.replaceFirstChar { it.uppercaseChar() }}"
//            }.forEach {
//                project.dependencies.add(it, "com.rickclephas.kmp:kmp-nativecoroutines-ksp:$VERSION")
//            }
```
It should be a problem caused by ksp dependencies. I found this feedback in the ksp project issues, but I don't know how to solve this problem.
The issues link is as follows：https://github.com/google/ksp/issues/60

**Comment by weijunfeng** [comment]
I solved this problem. I have the following configuration in my other .gradle files, 
```
tasks.whenObjectAdded { task ->
    if (task.name.equalsIgnoreCase('assembleRelease')) {
        task.group = "buildapk"
    } else if (task.name.equalsIgnoreCase('assembleDebug')) {
        task.group = "buildapk"
    }
}
```
The issue was resolved when I commented out this code，but I don't know why

Thank you for your reply

**Comment by rickclephas** [comment]
I have been working on some improvements to the KMP-NativeCoroutines Gradle plugin, making sure that it's evaluating everything lazily.

Unfortunately it didn't solve this particular issue, but I did notice something: `whenObjectAdded` is eagerly realising the tasks. Using `configureEach` or `named` instead will configure the tasks lazily which solves the issue.

Hope that helps!
